FROM python

WORKDIR /flaskAPI
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
EXPOSE 5001
COPY . .

CMD [ "python3", "-m", "FlaskAPI", "run",  "--host=0.0.0.0"]